-- ============================================================
-- Migration : V2__create_users.sql
-- Version   : P01 v2
-- Purpose   : Create users table for Login/Logout feature.
--             Stores username, salted SHA-256 password hash,
--             role, and audit timestamps.
-- Rollback  : db/rollback/V2__rollback_users.sql
-- ============================================================

-- Create the users table
-- Each row represents one application user (customer or admin).
CREATE TABLE users (
    id              SERIAL          PRIMARY KEY,
    username        VARCHAR(50)     NOT NULL,
    password_hash   VARCHAR(200)    NOT NULL,
    password_salt   VARCHAR(100)    NOT NULL,
    role            VARCHAR(20)     NOT NULL DEFAULT 'CUSTOMER',
    full_name       VARCHAR(100)    NOT NULL,
    email           VARCHAR(100)    NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    last_login      TIMESTAMP
);

-- Constraints follow project naming standard:
--   pk  = id (already defined as PRIMARY KEY above)
--   uq  = uq_<table>_<col>
--   chk = chk_<table>_<rule>
ALTER TABLE users
    ADD CONSTRAINT uq_users_username
        UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uq_users_email
        UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT chk_users_role
        CHECK (role IN ('CUSTOMER', 'ADMINISTRATOR'));

-- Index on username — every login does a WHERE username = ?
-- This makes that lookup fast even as the users table grows.
CREATE INDEX idx_users_username ON users (username);

-- ── Seed Users ──
-- Passwords below are SHA-256(salt + password).
-- Salt and hash are generated by the Java utility class
-- PasswordUtil.java (delivered in Sprint 2).
--
-- Seed user 1: customer account
--   username : customer1
--   password : Customer@123
--   salt     : a1b2c3d4e5f6a1b2
--   hash     : stored below (pre-computed)
--
-- Seed user 2: administrator account
--   username : admin1
--   password : Admin@123
--   salt     : f6e5d4c3b2a1f6e5
--   hash     : stored below (pre-computed)
--
-- NOTE: These salts and hashes are pre-computed placeholders.
-- Sprint 2's LoginServlet uses PasswordUtil.hash(salt, password)
-- to verify. The actual hash values are inserted by the Java
-- seed script delivered in Sprint 2 Step 1 — this migration
-- creates the table structure only, then inserts placeholder
-- rows that Sprint 2 replaces with correctly hashed values.

INSERT INTO users (
    username,
    password_hash,
    password_salt,
    role,
    full_name,
    email
) VALUES (
    'customer1',
    'PLACEHOLDER_REPLACED_IN_SPRINT2',
    'a1b2c3d4e5f6a1b2',
    'CUSTOMER',
    'Peta Venkatesh',
    'peta.venkatesh@digistack.cloud'
);

INSERT INTO users (
    username,
    password_hash,
    password_salt,
    role,
    full_name,
    email
) VALUES (
    'admin1',
    'PLACEHOLDER_REPLACED_IN_SPRINT2',
    'f6e5d4c3b2a1f6e5',
    'ADMINISTRATOR',
    'Admin User',
    'admin@digistack.cloud'
);
